package com.photon.phresco.util;

import java.io.File;
import java.io.IOException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.phloc.commons.io.file.SimpleFileIO;
import com.phloc.commons.state.ESuccess;
import com.phloc.css.ECSSVersion;
import com.phloc.css.decl.CascadingStyleSheet;
import com.phloc.css.writer.CSSWriter;
import com.phloc.css.writer.CSSWriterSettings;

/**
 * This is example code to write a CSS declaration to a {@link File}.
 * 
 * @author philip
 */
public final class ThemeBuilderWriteCSS
{

  /**
   * Write a CSS 3.0 declaration to a file using UTF-8 encoding.
   * 
   * @param aCSS
   *        The CSS to be written to a file
   * @param aFile
   *        The file to be written. May not be <code>null</code>.
   * @return {@link ESuccess#SUCCESS} if everything went okay, and
   *         {@link ESuccess#FAILURE} if an error occurred
   */
  public static ESuccess writeCSS30 (final CascadingStyleSheet aCSS, final File aFile)
  {
    // 1.param: version to write
    // 2.param: false== non-optimized output
    final CSSWriterSettings aSettings = new CSSWriterSettings (ECSSVersion.CSS30, false);
    try
    {
      final CSSWriter aWriter = new CSSWriter (aSettings);
      // Write the @charset rule: (optional)
//      aWriter.setContentCharset ("utf-8");
      // Write a nice file header
//      aWriter.setHeaderText ("This file was generated by phloc-css\nGrab a copy at http://code.google.com/p/phloc-css");
      // Convert the CSS to a String
      final String sCSSCode = aWriter.getCSSAsString (aCSS);
      // Finally write the String to a file
      System.out.println("Theme Builder Status--->"+ESuccess.SUCCESS);
      return SimpleFileIO.writeFile (aFile, sCSSCode, "utf-8");
    }
    catch (final IOException ex)
    {
    	System.out.println("Theme Builder Status--->"+ESuccess.FAILURE);
      return ESuccess.FAILURE;
    }
  }
}