/**
 * Phresco Commons
 *
 * Copyright (C) 1999-2014 Photon Infotech Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.26 at 11:55:11 AM IST 
//


package com.photon.phresco.plugins.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photon.jaxb.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photon.jaxb.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Name }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Name createMojosMojoConfigurationParametersParameterName() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Name();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter createMojosMojoConfigurationParametersParameter() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters createMojosMojoConfigurationParameters() {
        return new Mojos.Mojo.Configuration.Parameters();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter.Dependencies }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter.Dependencies createMojosMojoConfigurationParametersParameterDynamicParameterDependencies() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter.Dependencies();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs createMojosMojoConfigurationParametersParameterChilds() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter createMojosMojoConfigurationParametersParameterChildsChildDynamicParameter() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter();
    }

    /**
     * Create an instance of {@link Mojos.Mojo }
     * 
     */
    public Mojos.Mojo createMojosMojo() {
        return new Mojos.Mojo();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.PossibleValues }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.PossibleValues createMojosMojoConfigurationParametersParameterChildsChildPossibleValues() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.PossibleValues();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.MavenCommands }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.MavenCommands createMojosMojoConfigurationParametersParameterMavenCommands() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.MavenCommands();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues createMojosMojoConfigurationParametersParameterPossibleValues() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter createMojosMojoConfigurationParametersParameterDynamicParameter() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child createMojosMojoConfigurationParametersParameterChildsChild() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Implementation.Dependency }
     * 
     */
    public Mojos.Mojo.Implementation.Dependency createMojosMojoImplementationDependency() {
        return new Mojos.Mojo.Implementation.Dependency();
    }

    /**
     * Create an instance of {@link Mojos.ApplicationHandler }
     * 
     */
    public Mojos.ApplicationHandler createMojosApplicationHandler() {
        return new Mojos.ApplicationHandler();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter.Dependencies.Dependency }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter.Dependencies.Dependency createMojosMojoConfigurationParametersParameterDynamicParameterDependenciesDependency() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParameter.Dependencies.Dependency();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter.Dependencies }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter.Dependencies createMojosMojoConfigurationParametersParameterChildsChildDynamicParameterDependencies() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter.Dependencies();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Implementation }
     * 
     */
    public Mojos.Mojo.Implementation createMojosMojoImplementation() {
        return new Mojos.Mojo.Implementation();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues.Value }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues.Value createMojosMojoConfigurationParametersParameterPossibleValuesValue() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues.Value();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.Name }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.Name createMojosMojoConfigurationParametersParameterChildsChildName() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.Name();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.PossibleValues.Value }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.PossibleValues.Value createMojosMojoConfigurationParametersParameterChildsChildPossibleValuesValue() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.PossibleValues.Value();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration }
     * 
     */
    public Mojos.Mojo.Configuration createMojosMojoConfiguration() {
        return new Mojos.Mojo.Configuration();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value createMojosMojoConfigurationParametersParameterNameValue() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.MavenCommands.MavenCommand }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.MavenCommands.MavenCommand createMojosMojoConfigurationParametersParameterMavenCommandsMavenCommand() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.MavenCommands.MavenCommand();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter.Dependencies.Dependency }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter.Dependencies.Dependency createMojosMojoConfigurationParametersParameterChildsChildDynamicParameterDependenciesDependency() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.DynamicParameter.Dependencies.Dependency();
    }

    /**
     * Create an instance of {@link Mojos }
     * 
     */
    public Mojos createMojos() {
        return new Mojos();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.Name.Value }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.Name.Value createMojosMojoConfigurationParametersParameterChildsChildNameValue() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.Childs.Child.Name.Value();
    }

}
